config/routes.rb
Rails.application.routes.draw do

  get 'responses/ranking' => 'responses#ranking'
  resources :responses 
  resources :questions
  resources :users

  root 'welcome#index'
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :projects, controller: "projects"
  get "/your_projects" => "projects#your_projects", as: "your_projects"
  post "projects/add_users" => "projects#add_users", as: "add_users"
  post "projects/complete_project" => "projects#complete_project", as: "complete_project"
  get "/user" => "users#user_profile", as: "user_profile"
  get '/users/upload' => 'users#upload_avatar', as: 'upload_avatar'
  get '/your_reviews' => 'users#your_reviews', as: 'your_reviews'
end

app/models/project.rb
class Project < ApplicationRecord
   has_and_belongs_to_many :users
   has_many :responses 
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	def new
		@project = Project.new
	end

	def create
		@user = current_user
		@project = Project.new(project_params)
		@project.owner_id = @user.id
		@project.completed = false

		if @project.save
			@user.projects << @project
			redirect_to your_projects_path, :flash => { :success => "'#{@project.name}' successfully created!" }
		else
			render "new", :flash => { :error => "Failed to create '#{@project.name}'" }
		end
	end

	def edit
		@project = Project.find(params[:id])
	end

	def update
		@project = Project.find(params[:id])
		if @project.update(project_params)
			redirect_to project_path(@project.id), :flash => { :success => "Project successfully updated!" }
		else
			redirect_to edit_project_path(@project.id), :flash => { :error => "Failed to update project" }
		end
	end

	def destroy
		@project = Project.find(params[:id])
		if @project.destroy
			redirect_to your_projects_path, :flash => { :notice => "#{@project.name} successfully deleted"}
		end
	end

	def index
		@projects = Project.order(deadline: :DESC)
		@users = User.all
		@completed_reviews = Review.where(reviewed: true)
	end

	def show
		if current_user == nil
			redirect_to sign_in_path, :flash => { :error => "Please sign in to continue"}
		end
		@project = Project.find(params[:id])
		@project_users = @project.users.where("user_id NOT IN (?)", [@project.owner_id])
		@project_owner = User.find(@project.owner_id)
		@user_excluded_list = [@project_owner]
		@project_users.each do |user|
			@user_excluded_list << user.id
		end
		@users = User.where("id NOT IN (?)", @user_excluded_list)
		if current_user != nil
			@reviews = Review.where("project_id = ? AND sender_id = ? AND reviewed = ?", @project.id, current_user.id, false)
		end
	end

	def complete_project
		@project = Project.find(params[:project_id])
		@project.completed = true
		if @project.save
			@project.users.each do |sender|
				@project.users.where.not(id: sender.id).each do |recipient|
					Review.create([project_id: @project.id, sender_id: sender.id, recipient_id: recipient.id])
				end
			end

			redirect_to project_path(@project.id), :flash => { :success => "#{@project.name} completed!"}
		else
			redirect_to project_path(@project.id), :flash => { :error => "Failed to complete #{@project.name}!"}
		end
	end

	def your_projects
		@user = current_user
		@projects = @user.projects
	end

	def add_users
		@user = User.find(params[:user_id])
		@project = Project.find(params[:project_id])
		if @project.users << @user
			redirect_to project_path(@project.id), :flash => { :success => "#{@user.name} successfully added to #{@project.name}!"}
		else
			redirect_to project_path(@project.id), :flash => { :error => "Failed to add #{@user.name} to #{@project.name}!"}
		end
	end

	private
	def project_params
		params.require(:project).permit(:name, :description, :deadline, :budget)
	end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<div class="text-field form-group">
  <%= form.label :name %>
  <%= form.text_field :name, class: "form-control", placeholder: "Please enter project name" %>
</div>

<div class="text-field form-group">
  <%= form.label :description %>
  <%= form.text_area :description, class: "form-control", rows: "5", placeholder: "Please enter project description" %>
</div>

<div class="number-field form-group">
	<%= form.label :budget %>
	<%= form.number_field :budget, class: "form-control", placeholder: "Please enter project budget" %>
</div>

<div class="datetime-field form-group">
  <%= form.label :deadline %>
  <%= form.datetime_field :deadline, class: "form-control" %>
</div>

app/views/projects/edit.html.erb
<div class="container">
	<div class="row">
		<h1>Edit Project</h1>
	</div>
	<div class="row">
		<%= form_for @project, method: :patch, controller: "projects#update", html: {class: "col-6"} do |form|%>
		<%= render partial: '/projects/form', object: form %>

	    <div class="submit-field">
	      <%= form.submit "Edit Project", class: "btn btn-primary" %>
	    </div>

  		<% end %>	
	</div>
</div>

app/views/projects/index.html.erb
<div class="project-body pb-1">
	<div class="col-md-12 text-center p-2">
		<h1>All Projects</h1>
	</div>



	<div class="container card-list row">
		<div class="card blue col-md-4 border-0 rounded-0">
			<div class="title">all projects</div><span class="glyphicon glyphicon-upload"></span>
			<div class="value"><%=@projects.count%></div>
		</div>
		<div class="card green col-md-4 border-0 rounded-0">
			<div class="title">team members</div><span class="glyphicon glyphicon-upload"></span>
			<div class="value"><%=@users.count%></div>
		</div>
		<div class="card orange col-md-4 border-0 rounded-0">
			<div class="title">reviews submitted</div><span class="glyphicon glyphicon-download"></span>
			<div class="value"><%=@completed_reviews.count%></div>
		</div>
	</div><br>

	<div class="container projects mb-2">
		<div class="row projects-inner col-md-12">
			<header class="projects-header row">

			<div class="count mr-auto pl-2"><h5><%=@projects.count%> Projects</h5></div><span class="glyphicon glyphicon-download-alt"></span>
			</header>
			<table class="projects-table">
				<thead>
					<tr>
						<th>Project</th>
						<th>Deadline</th>
						<th>Leader</th>
						<th>Status</th>
					</tr>
				</thead>

			<% @projects.each do |p| %>
			<% project_owner = User.find(p.owner_id) %>
			<tr>
				<td>
				<p><%= link_to "#{p.name}", project_path(id: p.id), class: "project-links"%></p>

				</td>
				<td>
				<p><%=p.deadline%></p>
				<p class="danger-text"><%= Time.current > p.deadline ? "Overdue" : nil %></p>
				</td>
				<td class="member">
				<figure><img src="<%= project_owner.avatar %>"/></figure>
				<div class="member-info">
					<p class="pt-1"><%= link_to "#{project_owner.name}", user_path(id: p.owner_id), class: "project-links"%></p>
				</div>
				</td>
				<td class="project-status">
					<% if p.completed == true %>
					 	<div class="status-text status-green">"Completed"</div>
					<% else %>
					 	<div class="status-text status-orange">"In progress"</div>
					<% end %>					
				</div>
				<!-- <form class="form" action="#" method="POST">
					<select class="action-box">
					<option>Actions</option>
					<option>Start project</option>
					<option>Send for QA</option>
					<option>Send invoice</option>
					</select>
				</form> -->
				</td>
			</tr>

<% end %>
			</table>
		</div>
	</div>

</div>

app/views/projects/new.html.erb
<div class="container">
	<div class="row">
		<h1>New Project</h1>
	</div>
	<div class="row">
		<%= form_for @project, html: {class: "col-6"} do |form|%>
		<%= render partial: '/projects/form', object: form %>

	    <div class="submit-field">
	      <%= form.submit "New Project", class: "btn btn-primary" %>
	    </div>

  		<% end %>	
	</div>
</div>

app/views/projects/show.html.erb
<div class="container">
	<div class="row"><h1><%= @project.name %></h1></div>
	<div class="row"><p><%= @project.description %></p></div>
	<div class="row">
		<div class="m-2">DEADLINE: <%= @project.deadline %></div>
		<% if current_user == @project_owner %>
			<div class="mx-1"><%= button_to "Edit Project", edit_project_path(@project.id), class: "btn btn-secondary", method: :get %></div>
			<div class="mx-1"><%= button_to "Delete Project", project_path(@project.id), class: "btn btn-secondary", method: :delete %></div>
		<% end %>
	</div>
</div>

<hr>

<div class="container my-4">
	<div class="row">
			<div class="h2">Project owner</div>
	</div>
	<div class="row">

		<div class="m-2 bg-light px-auto">
			<div class=""><img src="<%=@project_owner.avatar%>" width="130px" class="rounded"></div>
		</div>
			<div class="pl-4 pt-5 h3" style="padding-right: 75px;"><%= @project_owner.name %></div>
		<% if current_user != @project_owner && @project.completed == true %>
			<% review = Review.find_by("project_id = ? AND sender_id = ? AND recipient_id = ?", @project.id, current_user.id, @project_owner.id) %>
			<% if review.reviewed == false%>
				<div class="pl-4 col-sm" style="padding-top: 42px;"><%= link_to "Review!", new_response_path(user_id: @project_owner.id, project_id: @project.id), class: "btn btn-primary" %></div>
			<% else %>
				<div class="pl-4 col-sm" style="color: green; padding-top: 55px;">Already reviewed!</div>
			<% end %>

		<% end %>
	</div>
</div>

	
<div class="container">
	<div class="row">
		<div class="h2">Team members</div>
	</div>

	<div class="row py-3 pl-4">
		<%= form_tag add_users_path, :method => :post do %>
			<input type="hidden" value="<%=@project.id%>" name="project_id">
			<%= select_tag 'user_id', options_for_select(@users.collect{ |u| [u.name, u.id] }), id: "add-users-select" %>
			<%= submit_tag "Add members", class: "btn btn-primary", id: "project-add-users-btn" %>
		<% end %>
	</div>



<% @project_users.each do |user| %>
	<div class="row">
		<div class="m-2 bg-light px-auto">
			<div class=""><img src="<%= user.avatar %>" width="100px" class="rounded-circle"></div>
		</div>
		<div class="pl-4 pt-5 h3 col-sm-2"><%= user.name %></div>
		<div>
			<% if user != current_user && @project.completed == true %>
				<% review = Review.find_by("project_id = ? AND sender_id = ? AND recipient_id = ?", @project.id, current_user.id, user.id) %>
				<% if review.reviewed == false%>
					<div class="pl-4 col-sm" style="padding-top: 42px;"><%= link_to "Review!", new_response_path(user_id: user.id, project_id: @project.id), class: "btn btn-primary" %></div>
				<% else %>
					<div class="pl-4 col-sm" style="color: green; padding-top: 55px;">Already reviewed!</div>
				<% end %>
			<% end %>
		</div>
	</div>
	<% end %>
</div>

<hr>

<div class="container">
	<% if @project.completed == false %>
		<div class="h2">STATUS: IN PROGRESS</div>
	<% else %>
		<div class="h2">STATUS: COMPLETED</div>
	<% end %>
	
	<% if current_user == @project_owner && @project.completed == false%>
		<div id="project-complete">
			<%= form_tag complete_project_path, :method => :post do %>
				<input type="hidden" value="<%=@project.id%>" name="project_id">
				<%= submit_tag "Complete project", class: "btn btn-primary" %>
			<% end %>
		</div>
	<% end %>
</div>

app/views/projects/your_projects.html.erb
<div class="project-body pb-1">
	<div class="col-md-12 text-center p-2">
		<h1>Your Projects</h1>
	</div>

	<div class="container projects mb-2">
		<div class="row projects-inner col-md-12">
			<header class="projects-header row">

			<div class="count mr-auto pl-2"><h5><%=@projects.count%> Projects</h5></div><span class="glyphicon glyphicon-download-alt"></span>
			</header>
			<table class="projects-table">
				<thead>
					<tr>
						<th>Project</th>
						<th>Deadline</th>
						<th>Status</th>
					</tr>
				</thead>

			<% @projects.each do |p| %>
			<% project_owner = User.find(p.owner_id) %>
			<tr>
				<td>
				<p><%= link_to "#{p.name}", project_path(id: p.id), class: "project-links"%></p>

				</td>
				<td>
				<p><%=p.deadline%></p>
				<p class="danger-text"><%= Time.current > p.deadline ? "Overdue" : nil %></p>
				</td>
				
				<td class="project-status">
					<% if p.completed == true %>
					 <div class="status-text status-green">"Completed"</div>
					 <form class="form" action="/projects/<%=p.id%>" method="GET">
							<select class="action-box" style="min-width: 170px;">
							<option>Actions</option>
							<option>Review members</option>
							</select>
							<input type="submit" value="Submit">
					</form>
					<% else %>
					 <div class="status-text status-orange">"In progress"</div>
					 <form class="form" action="/projects/<%=p.id%>" method="GET">
							<select class="action-box" style="min-width: 170px;">
							<option>Actions</option>
							<option>Add users</option>
							</select>
							<input type="submit" value="Submit">

					</form>
					<% end %>
				
				</td>
			</tr>

<% end %>
			</table>
		</div>
	</div>

</div>