config/routes.rb
Rails.application.routes.draw do

  get 'responses/ranking' => 'responses#ranking'
  resources :responses 
  resources :questions
  resources :users

  root 'welcome#index'
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :projects, controller: "projects"
  get "/your_projects" => "projects#your_projects", as: "your_projects"
  post "projects/add_users" => "projects#add_users", as: "add_users"
  post "projects/complete_project" => "projects#complete_project", as: "complete_project"
  get "/user" => "users#user_profile", as: "user_profile"
  get '/users/upload' => 'users#upload_avatar', as: 'upload_avatar'
  get '/your_reviews' => 'users#your_reviews', as: 'your_reviews'
end

app/views/layouts/_navigation.html.erb
<div id="goddamn-navigation">
    <nav class="navbar-expand-lg navbar-light row nav-padding">
            <a class="navbar-brand"<%= link_to image_tag("logo.png", id:"logo", class:"d-inline-block align-baseline mr-2", width:"20", height:"30") + "Evalist", root_path %></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    <% if current_user.nil? %>
                    <% else %>
                    <a class="nav-link"<%= link_to 'New Project', new_project_path, method: :get %></a>
                    <% end %>
                    <a class="nav-link"<%= link_to 'View Projects', projects_path, method: :get %></a>
                    <a class="nav-link"<%= link_to 'View Users', users_path, method: :get %></a>

                    <% if current_user.nil? %>

                    <a class="nav-link"<%= link_to 'Signup', sign_up_path, method: :get %></a>
                    <a class="nav-link"<%= link_to 'Sign in', sign_in_path, method: :get %></a>
                    
                    <% else  %>
                        <!-- <li class="nav-item"><span class="navbar-text">Logged in as</span></li> -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            
                                <%= current_user.name  %>
                            </a>
                            <div class="dropdown-menu " aria-labelledby="navbarDropdown">
                                <a class="dropdown-item"<%= link_to 'My Profile', user_path(current_user) %> </a>
                                <a class="dropdown-item"<%= link_to 'My Projects', your_projects_path %></a>
                                <a class="dropdown-item"<%= link_to 'My Reviews', your_reviews_path %></a>


                                
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item"><%= button_to 'Sign out', sign_out_path, method: :delete, class:"btn btn-primary" %></a>

                            </div>
                        </li>
                    
                    <% end %>
                </ul>

            </div>
    </nav>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="/css/bootstrap.css">
  <%= csrf_meta_tag %>
</head>
<body class="bg-light">

<%= render partial: 'layouts/navigation' %>

<% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %>">
            <%= value %>
      </div>
<% end %>

<div class="page-content">
  <%= yield %>
</div>
	<footer>
		<div>

		</div>
	  <div id="footer" class="text-center">
	    <div class="container">


	      	<div>
		      	<p>&copy; Copyright Evalist Group. All rights Reserved.</p>
		      	<div>
		        	Designed by Evalist Group
		     	 </div>
	  		</div>
	    </div>
	  </div>
	</footer>
</body>
</html>